apiVersion: v1
kind: Pod
metadata:
  name: link-extractor
spec:
  containers:
    - name: link-extractor
      image: imaneaity/link-extractor:latest  #  DockerHub image because we pushed remotely
      args: ["-u", "https://news.ycombinator.com", "-o", "stdout"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
  restartPolicy: Never
